### ISSUE TITLE
Is "labels" attribute required for LineChart?

### ISSUE THREAD

**Issue by hshim** [Jpadilla1/react-native-ios-charts#3]
This is really helpful for my project. 
It seems like the "labels" attribute is not a requirement for LineChart, but if you omit this attribute, the chart will only draw the first two values of the "values" array, which is weird. 
Is this a bug? or is there some other way to omit the "labels" and just draw line chart of the "values"?
I'm letting the "labels" be values.length sized array of empty strings for now, but this seems too hacky.
Thanks!

**Comment by Jpadilla1** [comment]
I checked the example from https://github.com/danielgindi/ios-charts/blob/master/ChartsDemo/Classes/Demos/SinusBarChartViewController.m and to avoid show the labels you can either disable the axis or set drawLabels to false on the axis. That is what is done in this example, he sets the xAxis to be false on this line https://github.com/danielgindi/ios-charts/blob/master/ChartsDemo/Classes/Demos/SinusBarChartViewController.m#L61, but still has to set the labels (xVals) array https://github.com/danielgindi/ios-charts/blob/master/ChartsDemo/Classes/Demos/SinusBarChartViewController.m#L99-L116

As for the property, it should be required.

**Comment by hshim** [comment]
Hey,

Thanks for the reply. But I think you are talking about the "label" attribute within xAxis or yAxis. 
There's another attribute called "labels" which is a global config under LineChart (Just like the one you used in the example code under BarChart; you have `labels: ['a', 'b', 'c', 'd']`, which isn't under any axes).
In LineChart, if you omit this attribute, only first two values will be plotted and the rest cut out. I don't think this is expected behavior. Am I somehow mistaken?

Thanks.

**Comment by Jpadilla1** [comment]
Actually the "labels" attribute that you are mentioning is the one used in the xAxis it's just not set explicitly like `self.xAxis.labels`. The labels attribute is equal to the xVals property in the DataSet class for the Bar & Line Chart. I agree that this should not be the expected behavior, but it is what I have found by looking at the examples in ios-charts and the class properties.

If you do find a way please let me know, because I also find it unnecessary to pass a labels array with the same length to not show them.

Hope this helps!
